import {
  INGREDIENT_URL_COCKTAILS,
  INGREDIENT_URL_MEALS,
  NAME_URL_COCKTAILS,
  NAME_URL_MEALS,
  FIRST_LETTER_URL_COCKTAILS,
  FIRST_LETTER_URL_MEALS,
} from './filterAPI';

export const URL_MEALS = [INGREDIENT_URL_MEALS, NAME_URL_MEALS, FIRST_LETTER_URL_MEALS];
export const URL_COCKTAILS = [
  INGREDIENT_URL_COCKTAILS,
  NAME_URL_COCKTAILS,
  FIRST_LETTER_URL_COCKTAILS
];
